# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Byverdu
tagline:          '|| Vallverdu'
description:      'There is no place like GitHub'
url:              http://byverdu.github.io/
baseurl:          /

author:
  name:           'Albert Vallverdu'
  url:            https://twitter.com/byverdu

paginate:         5

sass:
  style: :compressed

excerpt_separator: "<!-- more -->"

# Custom vars
version:             1.0.0

github_repo: https://github.com/byverdu/byverdu.github.io.git